application: yaki-gae
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- appstats: on
- deferred: on

handlers:
- url: /static
  static_dir: themes/ink/static

- url: /.*
  script: app.app
